DEFAULT_BOOK_ID = 1578
DEFAULT_MODEL_PARAMS = {'tag_': 0, 'sen_': 50, 'users':0, 'jaccard': 50, 'book_rating_value': 10, 'book_nb_comm': 0, 'book_rating_count': 0}
MAX_TO_PREDICT = 10
URL_ROOT_WEBSITE = 'https://www.babelio.com'
BOOK_FILE = '../output/final/data-books.json'
COMM_FILE = '../output/final/data-comm-light.json'
MODEL_FILE = '../output/final/model-reco.obj'
DB_FILE = '../output/final/data.db'
SERVER_PORT = '8080'